name: build-and-test

on:
  push:
    branches:
      - feature/**
  pull_request:
    branches:
      - feature/**
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT_BOTCOW: ${{ secrets.BOTCOW_GITHUB_PAT }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      BLOB_READ_WRITE_TOKEN: ${{ secrets.BLOB_READ_WRITE_TOKEN }}
      BOTCOW_DEFAULT_REPO: ${{ secrets.BOTCOW_DEFAULT_REPO }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: npm ci

      - name: Test
        run: npm test

      - name: Build
        run: npm run build
